export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_BOOK_LIST = 'UPDATE_BOOK_LIST';
export const USE_CACHE = 'USE_CACHE';
export const CLEAR_CACHE = 'CLEAR_CACHE';
export const LOADING_STATUS = 'LOADING_STATUS';